
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8088/eureka/
#  server:
#    enableSelfPreservation: false
#    renewalPercentThreshold: 0.49
#    waitTimeInMsWhenSyncEmpty: 0

#  instance:
#    leaseRenewalIntervalInSeconds: 1
#    leaseExpirationDurationInSeconds: 2


#  instance:
#    environment: test_school


#    server:
#      waitTimeInMsWhenSyncEmpty: 0