spring:
  application:
    name: view-outcontrol

server:
  port: 8009

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8088/eureka/
  instance:
    hostname: localhost

#hystrix:
#  command:
#    start-verification:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 600000


hystrix:
  command:
    view-outControl:
    execution:
      isolation:
        strategy: THREAD
        thread:
          timeoutInMilliseconds: 95000

start-verification:
  ribbon:
    ConnectTimeout: 30000
    ReadTimeout: 60000
    MaxTotalHttpConnections: 500
    MaxConnectionsPerHost: 100